name: Autograding Tests
on:
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      run: |
        docker run --name ku-mysql \
        -e MYSQL_ROOT_PASSWORD=admin \
        -d -p 3306:3306 mysql:8.0.33

    - name: Wait for MySQL to be ready
      run: |
        until docker exec ku-mysql mysqladmin ping -h "127.0.0.1" --silent; do
          echo "Waiting for MySQL..."
          sleep 5
        done

    - name: Load database schema
      run: |
        docker exec -i ku-mysql mysql -uroot -padmin -h127.0.0.1 < load.sql
        
    - name: Run and Compare q1.sql
      run: |
        docker exec -i ku-mysql mysql -uroot -padmin -s classicmodels < submission/q1.sql > student-q1-result.txt
        diff -w student-q1-result.txt solutions/q1-sol.out
